server:
  port: ${APPLICATION_PORT:8081}
  tomcat:
    max-swallow-size: ${TOMCAT_MAX_SWALLOW_SIZE:-1}
    max-part-count: ${TOMCAT_MAX_PART_COUNT:-1}

spring:
  application:
    name: ${APPLICATION_NAME:cloud-storage}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cloud-storage-db}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    open-in-view: ${OPEN_IN_VIEW:false}

  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      session-max-inactive-interval: ${USER_SESSION_MAX_INACTIVE_INTERVAL:30m}

  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:3GB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:3GB}

multipart-files-count-limit: ${MULTIPART_FILES_COUNT_LIMIT:50}

security:
  cors:
    apply-pattern: ${CORS_APPLY_PATTERN:/**}
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}
    allowed-methods: ${CORS_ALLOWED_METHODS:*}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

  open-endpoints:
    POST: ${POST_OPEN_ENDPOINTS:/api/auth/sign-in, /api/auth/sign-up}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:user}
  secret-key: ${MINIO_SECRET_KEY:password}