server:
  port: ${APPLICATION_PORT:8081}

spring:
  application:
    name: cloud-storage

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cloud-storage-db}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    open-in-view: ${OPEN_IN_VIEW:false}

  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      session-max-inactive-interval: ${USER_SESSION_MAX_INACTIVE_INTERVAL:30m}

security:
  cors:
    apply-pattern: ${CORS_APPLY_PATTERN:/**}
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8080}
    allowed-methods: ${CORS_ALLOWED_METHODS:*}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

  open-endpoints:
    POST: ${POST_OPEN_ENDPOINTS:/api/auth/sign-in, /api/auth/sign-up}
