# --- Versions ---
[versions]
spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"

postgresql = "42.7.8"
minio = "8.6.0"

lombok = "1.18.42"
mapstruct = "1.6.3"
lombok-mapstruct-binding = "0.2.0"

testcontainers-junit-jupiter = "1.21.3"
testcontainers-postgresql = "1.21.3"
testcontainers-redis = "2.2.4"

# --- Plugins ---
[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

# --- Libraries ---
[libraries]
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-data-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis", version.ref = "spring-boot" }
spring-boot-starter-liquibase = { group = "org.springframework.boot", name = "spring-boot-starter-liquibase", version.ref = "spring-boot" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version.ref = "spring-boot" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-starter-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test", version.ref = "spring-boot" }

spring-boot-testcontainers = { group = "org.springframework.boot", name = "spring-boot-testcontainers", version.ref = "spring-boot" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers-junit-jupiter"}
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers-postgresql"}
testcontainers-redis = { group = "com.redis", name = "testcontainers-redis", version.ref = "testcontainers-redis"}

spring-session-data-redis = { group = "org.springframework.session", name = "spring-session-data-redis", version.ref = "spring-boot" }

postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
minio = { group = "io.minio", name = "minio", version.ref = "minio" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }

lombok-mapstruct-binding = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }

# --- Bundles ---
[bundles]
spring-boot-starters = [
    "spring-boot-starter", "spring-boot-starter-web", "spring-boot-starter-data-jpa", "spring-boot-starter-data-redis",
    "spring-boot-starter-liquibase", "spring-boot-starter-validation", "spring-boot-starter-security"
]

spring-boot-test-starters = ["spring-boot-starter-test", "spring-boot-starter-webmvc-test"]

testcontainers = [
    "spring-boot-testcontainers", "testcontainers-junit-jupiter", "testcontainers-postgresql", "testcontainers-redis"
]